// <auto-generated />
using System;
using APIArkanoid.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIArkanoid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403094623_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIArkanoid.Models.BallSkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TexturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BallSkins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            Name = "Default",
                            Price = 0,
                            TexturePath = "default"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            Name = "Fire",
                            Price = 100,
                            TexturePath = "fire"
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = false,
                            Name = "Ice",
                            Price = 150,
                            TexturePath = "ice"
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = false,
                            Name = "Galaxy",
                            Price = 200,
                            TexturePath = "galaxy"
                        });
                });

            modelBuilder.Entity("APIArkanoid.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APIArkanoid.Models.UserBallSkin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BallSkinId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "BallSkinId");

                    b.HasIndex("BallSkinId");

                    b.ToTable("UserBallSkins");
                });

            modelBuilder.Entity("APIArkanoid.Models.UserBallSkin", b =>
                {
                    b.HasOne("APIArkanoid.Models.BallSkin", "BallSkin")
                        .WithMany()
                        .HasForeignKey("BallSkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIArkanoid.Models.User", "User")
                        .WithMany("OwnedSkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BallSkin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIArkanoid.Models.User", b =>
                {
                    b.Navigation("OwnedSkins");
                });
#pragma warning restore 612, 618
        }
    }
}
